import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrencyFull } from './formatters';

export const generateReportPDF = (reportData: any, shopDetails: any, dateRange: { start: string, end: string }) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40);
    doc.text(`${shopDetails.name || 'Lenden App'} - Business Report`, 14, 22);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 30);
    doc.text(`Period: ${dateRange.start} to ${dateRange.end}`, 14, 35);

    // Summary Table
    const summaryData = [
        ['Total Sales', formatCurrencyFull(reportData.total_sales || 0, 'BDT')],
        ['Sales Count', (reportData.sales_count || 0).toLocaleString()],
        ['Total Expenses', formatCurrencyFull(reportData.total_expenses || 0, 'BDT')],
        ['Due Collected', formatCurrencyFull(reportData.due_collected || 0, 'BDT')],
        ['Gross Profit', formatCurrencyFull(reportData.gross_profit || 0, 'BDT')],
        ['Net Profit', formatCurrencyFull(reportData.net_profit || 0, 'BDT')],
        ['', ''], // Spacer
        ['Inventory Value', formatCurrencyFull(reportData.inventory_value || 0, 'BDT')],
        ['Product Count', (reportData.product_count || 0).toLocaleString()],
        ['Customer Count', (reportData.customer_count || 0).toLocaleString()],
        ['Total Due', formatCurrencyFull(reportData.total_due || 0, 'BDT')],
        ['Active Trips', (reportData.active_trips || 0).toLocaleString()],
        ['Vendor Count', (reportData.vendor_count || 0).toLocaleString()]
    ];

    autoTable(doc, {
        startY: 45,
        head: [['Metric', 'Value']],
        body: summaryData,
        theme: 'striped',
        headStyles: { fillColor: [37, 99, 235] },
        columnStyles: {
            0: { fontStyle: 'bold' },
            1: { halign: 'right' }
        }
    });

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    doc.setFontSize(8);
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.text(
            `Page ${i} of ${pageCount} - Generated by Lenden App`,
            doc.internal.pageSize.width / 2,
            doc.internal.pageSize.height - 10,
            { align: 'center' }
        );
    }

    // Save
    doc.save(`report_${dateRange.start}_to_${dateRange.end}.pdf`);
};
